# Generated by Django 4.0.3 on 2022-04-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myUrlShortner', '0002_shortlongurlstore_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlongurlstore',
            name='username',
            field=models.EmailField(max_length=30),
        ),
    ]
