# Generated by Django 4.0.3 on 2022-04-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myUrlShortner', '0003_alter_shortlongurlstore_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlongurlstore',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
